
[build]
cmd = "CGO_ENABLED=0 go build -mod=vendor -gcflags='all=-N -l' -o /tmp/debug_bin main.go"
bin = "/tmp/debug_bin"
full_bin = "dlv exec /tmp/debug_bin --accept-multiclient --log --headless --continue --listen :40000 --api-version 2"
send_interrupt = false
stop_on_error = true

[color]
build = "yellow"
main = "magenta"
runner = "green"
watcher = "cyan"

[log]
time = false

[misc]
clean_on_exit = false

[screen]
clear_on_rebuild = false